### ISSUE TITLE
witelive crashes on start 

### ISSUE THREAD

**Issue by zerocolTHS** [curlyboi/WinTelive#1]
Here is the error a  few users are facing any ideas ? 

`*************\* Exception Text **************
System.DllNotFoundException: Unable to load DLL 'libtetradec.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at wintelive.acelp.tetra_decode_init()
   at wintelive.acelp..ctor(receiver myParent)
   at wintelive.telive.rxEnumAll()
   at wintelive.telive.startAll()
   at wintelive.frmMain.btnInitGNR_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1085.0 built by: NETFXREL4STAGE
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

wintelive
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
##     CodeBase: file:///C:/Users/zc/Documents/sdr-tetra/wintelive/wintelive/wintelive.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1085.0 built by: NETFXREL4STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1085.0 built by: NETFXREL4STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1085.0 built by: NETFXREL4STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1085.0 built by: NETFXREL4STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1085.0 built by: NETFXREL4STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1085.0 built by: NETFXREL4STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

`

**Comment by curlyboi** [comment]
Do you have the DLL file?

**Comment by luihurgom** [comment]
Same error in my case

**Comment by curlyboi** [comment]
The DLL problem should have been solved a few days after the release so if you are still getting the error it's probably because you do not have the correct runtime or you don't have the DLL in the directory.

**Comment by luihurgom** [comment]
Finally it works for me, I guess the problem was I hand't installed the vc 2016 x86, only x64 and it wasn't enough. After install the x86 version it ran

**Comment by curlyboi** [comment]
perfect, closing. thanks for the report.
