### ISSUE TITLE
curlyboi's web server is down

### ISSUE THREAD

**Issue by bogdan-7** [curlyboi/WinTelive#12]
Hello, curlyboi. I want to download Wintelive tetra decoder, but your web server is down.
It says:
```

Not Found

The requested URL was not found on this server.
Apache/2.4.25 (Debian) Server at curly.100dola.eu Port 80

```
What should I do? I googled, but that seems to be the only site I can download Wintelive and its dependencies. I looked at other issues here, on github, but nothing helpful again. Can you bring your web server back running or you have another link to download Wintelive? Btw, your work is awesome.

![Wintelive web server error](https://user-images.githubusercontent.com/61235604/74837588-1b493f00-5322-11ea-86d2-c826166f0c5e.png)

**Comment by curlyboi** [comment]
hi. i believe there is now a tool to integrate tetra decoding directly into SDR# which is far better method. i have deleted a lot of old garbage from my server. you can still compile wintelive directly from this github source if you want
